apiVersion: v1
kind: Service
metadata:
  namespace: renchain
  name: bootnode-registrar
  labels:
    app: bootnode-registrar
spec:
  selector:
    app: bootnode-registrar
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9898
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootnode-registrar
  namespace: renchain
  labels:
    app: bootnode-registrar
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: bootnode-registrar
  template:
    metadata:
      labels:
        app: bootnode-registrar
    spec:
      containers:
        - name: bootnode-registrar
          image: jpoon/bootnode-registrar:v1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: BOOTNODE_SERVICE
              value: "bootnode.renchain.svc.cluster.local"
          ports:
            - containerPort: 9898